### ISSUE TITLE
Question about his@k

### ISSUE THREAD

**Issue by YangLi1221** [thunlp/HNRE#10]
I have already extracted a subset of the test dataset in which all the relations have fewer than 100/200 training instances. However, my reproduced results (according to your model that published on github) is not match the results on your paper. Would you mind giving me some notices?

**Comment by THUCSTHanxu13** [comment]
I have added the code for evaluating Hits@K. The released checkpoints can achieve comparable results with our reported ones (As the released checkpoints were also retrained on this toolkit, the random operations in training and test make it difficult to achieve identical results). You can have a try with our adding code.
