### ISSUE TITLE
error config

### ISSUE THREAD

**Issue by holoword** [thunlp/HNRE#2]
in file train line 18， their an error set of mode save path /output/ckpt/  which supposed be /outputs/ckpt

**Comment by lulu51230** [comment]
I run the pretrained model to get the result of pone, ptwo and pall. But all of them had a great gap with the results given in the paper.
Do you know how to solve this problem?please

**Comment by THUCSTHanxu13** [comment]
Some problems of the config and initialization code have been fixed. Now, the released checkpoints can achieve comparable results with our reported ones.
