### ISSUE TITLE
训练数据为什么是57w条，而论文里写的是52万

### ISSUE THREAD

**Issue by majingbit** [thunlp/HNRE#5]
使用该git raw_data下的57万数据训练出来的效果远远好于52万的训练数据，作者能解释下吗，非常感谢

**Comment by THUCSTHanxu13** [comment]
我们用的数据来源于https://github.com/tyliupku/soft-label-RE提供的https://pan.baidu.com/s/1dG3PAjn，这个数据是延续的attention模型的baseline（https://github.com/thunlp/NRE）一开始发布的数据。这个数据是nyt-10的原始版本，之前的模型是在这个数据上跑的，实验部分的数据说明也就直接照着之前论文汇报内容写的。

**Comment by THUCSTHanxu13** [comment]
最近我们在做一些实验，发现nyt-10的原始数据需要清理里57万和52万主要差距的地方是，训练集合里面会有部分entity pair和测试集合里面的entity pair重合，distant的句子不一样，部分entity pair还是na。所以用原始的训练集合，会让模型更好的判别na，整体结果会上升

**Comment by THUCSTHanxu13** [comment]
我们在https://github.com/thunlp/OpenNRE里复现了最近这几年的RE的论文模型，然后发现因为nyt-10数据的问题，大家的实验结果会有不少出入，nyt-10这个数据很难刻画模型效果。一方面是数据噪音很大，另一方面是很多entity-pair有关系但却标注为了NA。如果模型效果不错的话，你预测出这些entity-pair的关系，反而会引起效果下降

**Comment by THUCSTHanxu13** [comment]
18年在emnlp和大家交流的结果就是感觉re里面nyt-10这个数据不太可靠，大家也感觉用一个新的数据集做实验会更具有说服力。我倒是建议你用我们精标的一个数据集合，https://github.com/thunlp/FewRel ，再从wikipedia上distant一些数据构建新的数据来进行试验。

**Comment by majingbit** [comment]
了解了，所以大家论文里的对比实验是有点问题的，PCNN在57w上效果远不止论文里对比实验的结果
