### ISSUE TITLE
question about relation_level.npy

### ISSUE THREAD

**Issue by YaNjIeE** [thunlp/HNRE#6]
Hi, I am confused about the relation_level.npy file which is a 53X2 matrix.
Would you please explain it?
Thanks a lot.

Best :p

**Comment by Perfec-Yu** [comment]
Hi,

It corresponds to the relation hierarchy in the paper. Each row of the matrix corresponds to a relation  , it's parent node, grand-parent nodes, etc. For efficiency we only considered relation and it's parent relation, thus forming the 53x2 matrix. The parent relation is not explicitly given in the repo, as it is only manually constructed and have no formal names actually. But typically they are ones like "/person", which in this case has all the relations beginning with "/person/" as its children. I hope I have made it clearer to you.

Thanks

**Comment by YaNjIeE** [comment]
Now I get it. Thanks a lot. 

Have a good day : p
