### ISSUE TITLE
question about Hits@K

### ISSUE THREAD

**Issue by YaNjIeE** [thunlp/HNRE#7]
Hi, I am confused about  Hits@K metrics.
In the paper,  "accuracy (%) of Hits@K on relations with training instances fewer than 100/200." is written. 
I wonder that the long-tail relations is defined as the relations which training bags  are fewer than 100/200 or training sentences are fewer than 100/200? 

Thanks a lot.
Best.

**Comment by JunKuang-algo** [comment]
Hi, @yanjieG 
Have you solved this problem?

**Comment by THUCSTHanxu13** [comment]
I have added the code for evaluating Hits@K. The released checkpoints can achieve comparable results with our reported ones (As the released checkpoints were also retrained on this toolkit, the random operations in training and test make it difficult to achieve identical results). You can have a try with our adding code.
